services:
  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8181:8080"
    volumes:
      - ./searxng/config:/etc/searxng
      - ./searxng/cache:/var/cache/searxng
    environment:
      - SEARXNG_BASE_URL=http://localhost:8181
    networks:
      - searxng-network

  mcp-searxng:
    image: isokoliuk/mcp-searxng:latest
    depends_on:
      - searxng
    stdin_open: true
    environment:
      - SEARXNG_URL=http://searxng:8080
    networks:
      - searxng-network


networks:
  searxng-network:
    driver: bridge
