version         = 1

[*]
# General Settings
threads         = 8

# Generation Settings
predict         = -1
context-shift   = true
jinja           = true

# MCP Settings
# webui-mcp-proxy = true

[gemma4-E2B-Q4_K_M]
# Repo Settings
hf-repo         = unsloth/gemma-4-E2B-it-GGUF:Q4_K_M
# Generation Settings
ctx-size        = 32768
