version         = 1

[*]
# General Settings
threads         = 8
fit             = on

# Generation Settings
flash-attn      = on
predict         = -1
context-shift   = true
jinja           = true

# Speculative Decoding Settings
spec-type       = ngram-map-k4v
spec-ngram-map-k4v-size-n = 7
spec-ngram-map-k4v-size-m = 11

[gemma4-E2B-Q4_K_M]
# Model Settings
hf-repo         = unsloth/gemma-4-E2B-it-GGUF:Q4_K_M
# Generation Settings
ctx-size        = 32768

[gemma4-12B-Q4_K_M]
# Model Settings
hf-repo         = unsloth/gemma-4-12b-it-GGUF:Q4_K_M
load-on-startup = true
# Generation Settings
ctx-size        = 32768
